---
# https://docs.getdbt.com/docs/core/connect-data-platform/snowflake-setup
dbt_af_data_project:
  outputs:
    sf:
        # Instance
      type: snowflake
      account: "cgzbiai-iea50840"
        # Login
      user: "dskumar87"
        # Keypair config [private_key_path or private_key]
      password: "29121987@Suresh"
        # Execution Config
      role: "PUBLIC"
      database: "DBT_CLOUD"
      warehouse: "ADHR_DEV_WH"
      schema: SILVER
      threads: 2
      client_session_keep_alive: false
      query_tag: DBT

        # optional
      connect_retries: 0  # default 0
      connect_timeout: 10  # default: 10
      retry_on_database_errors: false  # default: false
      retry_all: false  # default: false
      reuse_connections: false  # default: false (available v1.4+)
  target: sf
  config:
    send_anonymous_usage_stats: false